/**
 * FileIcon — file/folder identity icon.
 *
 * Icons are Material Icon Theme (https://github.com/material-extensions/vscode-material-icon-theme)
 * by Philipp Kief, MIT licensed, consumed via the `material-icon-theme` npm package
 * (v5.37.0). This replaces the previous hand-mapped lucide glyphs for file/folder
 * *identity* per DESIGN-SPEC Amendments item 1 — lucide-react stays the icon set for
 * everything else (chevrons, git glyphs, gear, search, toolbar actions). The SVGs are
 * full-color by design and are never tinted/recolored.
 *
 * Resolution follows the same order VSCode's icon-theme host uses:
 *   - file:   `fileNames[basename.toLowerCase()]` -> longest matching
 *             `fileExtensions` suffix -> default `file`
 *   - folder: `folderNames`/`folderNamesExpanded` (closed/open) keyed by folder
 *             name -> default `folder`/`folder-open`
 *
 * Two tiers, so a cold boot is cheap but coverage stays generic:
 *   1. `materialIcons.curated.ts` (generated by `scripts/generate-icon-manifest.mjs`,
 *      see its header) is a small, hand-curated slice of the upstream manifest — the
 *      demo vault's own needs plus a "typical web/dev project" set — imported
 *      statically (a few KB) with one explicit lazy `import()` per curated icon. Most
 *      real vaults resolve entirely on this tier: instant, no network round trip for
 *      the *lookup*, only a tiny fetch per distinct icon actually rendered.
 *   2. Only when tier 1 can't name anything more specific than its own generic
 *      `file` default does `./materialIconLoader` get dynamically imported — the
 *      *full* ~450KB upstream manifest + an `import.meta.glob` over all ~1250 icons
 *      — to see if the full pack recognizes the file. This tier exists purely so an
 *      exotic extension still resolves correctly; the curated default already on
 *      screen is only *upgraded* if tier 2 finds something better, never blocked on
 *      it. Files only — folder *names* are effectively open-ended (a repo's root/
 *      subfolder names are as likely to be arbitrary as conventional, so even the
 *      full ~4650-entry `folderNames` map rarely adds a hit the curated ~26 names
 *      didn't already have), so an unmatched folder just keeps the curated default
 *      `folder`/`folder-open` glyph rather than spending 600KB on a fetch that,
 *      empirically, essentially never pays off — including for this app's own
 *      vault-root folder, which is exactly what first exposed the cost of doing it.
 * Earlier revisions of this component always loaded the full manifest + glob table
 * lazily; profiling showed that "lazy" only delayed those ~600KB by milliseconds
 * because the tree needs icons at first paint, so every cold boot paid for it anyway.
 * The curated tier exists specifically to avoid that.
 *
 * Not-found / load-failure is handled gracefully: resolution always has a concrete
 * fallback (the curated pack's own default `file`/`folder`/`folder-open` glyph), and
 * if even that fails to load (e.g. a broken install), a neutral lucide glyph renders
 * instead of a broken `<img>` or a crash — the same neutral glyph shown very briefly
 * while the first icon of a given kind is still being fetched.
 *
 * Logged in docs/COMPONENT-BACKLOG.md ("FileIcon", group `display`), used by
 * `ExplorerTree` and `EditorTabBar`.
 */
import { useEffect, useState } from "react";
import { File as FileFallbackGlyph, Folder as FolderFallbackGlyph } from "lucide-react";
import { curatedIconLoaders, curatedManifest, KIND_FALLBACK_EXT } from "./materialIcons.curated";
import type { FileKind } from "../../types";

interface CuratedResolution {
  key: string;
  /** False only when resolution fell all the way through to the curated
   * pack's own generic default (`file`/`folder`/`folder-open`) — signals
   * `FileIcon` to also try the full-manifest fallback in the background. */
  matched: boolean;
}

function resolveFileIconCurated(name: string | undefined, kind: FileKind): CuratedResolution {
  const lower = name?.toLowerCase();
  if (lower) {
    const byName = curatedManifest.fileNames[lower];
    if (byName) return { key: byName, matched: true };
    // Longest matching extension first: "a.b.c" tries "b.c" before "c".
    const parts = lower.split(".");
    for (let i = 1; i < parts.length; i++) {
      const ext = parts.slice(i).join(".");
      const hit = curatedManifest.fileExtensions[ext];
      if (hit) return { key: hit, matched: true };
    }
  }
  const fallbackExt = KIND_FALLBACK_EXT[kind];
  const hit = fallbackExt ? curatedManifest.fileExtensions[fallbackExt] : undefined;
  if (hit) return { key: hit, matched: true };
  return { key: curatedManifest.file, matched: false };
}

function resolveFolderIconCurated(name: string | undefined, open: boolean): CuratedResolution {
  const lower = name?.toLowerCase();
  const map = open ? curatedManifest.folderNamesExpanded : curatedManifest.folderNames;
  const hit = lower ? map[lower] : undefined;
  if (hit) return { key: hit, matched: true };
  return { key: open ? curatedManifest.folderExpanded : curatedManifest.folder, matched: false };
}

const curatedUrlCache = new Map<string, Promise<string | undefined>>();

function loadCuratedIconUrl(key: string): Promise<string | undefined> {
  const cached = curatedUrlCache.get(key);
  if (cached) return cached;
  const loader = curatedIconLoaders[key];
  const promise = loader ? loader().catch(() => undefined) : Promise.resolve(undefined);
  curatedUrlCache.set(key, promise);
  return promise;
}

export interface FileIconProps {
  kind: FileKind;
  /** The file/folder's actual basename — enables Material Icon Theme's real
   * filename/extension and folder-name resolution (e.g. `notes` -> `folder-docs`).
   * Optional for back-compat: without it, resolution falls back to `kind`'s
   * representative extension (files) or the generic folder glyph (folders). */
  name?: string;
  /** Folder open/expanded state — only meaningful for kind="folder". */
  open?: boolean;
  size?: number;
  className?: string;
}

export function FileIcon({ kind, name, open, size = 14, className }: FileIconProps) {
  const isFolder = kind === "folder";
  // Identity of the *request* (not the resolved icon) — used below to reset stale
  // state synchronously during render (React's documented "adjusting state when a
  // prop changes" pattern, the same one ExplorerTree's rename-snapshot reset uses)
  // so a prop change never flashes the *previous* icon before resolution redoes.
  const requestKey = `${kind}:${name ?? ""}:${open ? "1" : "0"}`;

  const [resolved, setResolved] = useState<{ key: string; src: string | undefined }>({
    key: requestKey,
    src: undefined,
  });
  const src = resolved.key === requestKey ? resolved.src : undefined;
  if (resolved.key !== requestKey) {
    setResolved({ key: requestKey, src: undefined });
  }

  useEffect(() => {
    let cancelled = false;

    const curated = isFolder ? resolveFolderIconCurated(name, !!open) : resolveFileIconCurated(name, kind);
    loadCuratedIconUrl(curated.key).then((url) => {
      if (!cancelled && url) setResolved({ key: requestKey, src: url });
    });

    if (!curated.matched && !isFolder) {
      // The curated table doesn't recognize this file — try the full upstream
      // manifest in the background (lazy: only reached on a real miss, and never
      // for folders — see this file's header) to see if a more specific icon
      // exists; upgrade to it if so, without ever blocking the curated default
      // already shown above.
      import("./materialIconLoader").then(async (loader) => {
        if (cancelled) return;
        const manifest = await loader.getManifest();
        if (cancelled) return;
        const betterKey = loader.resolveFileIconKey(manifest, name, curated.key);
        if (!betterKey) return; // full manifest agrees with the curated default
        const url = await loader.loadIconUrl(manifest, betterKey);
        if (!cancelled && url) setResolved({ key: requestKey, src: url });
      });
    }

    return () => {
      cancelled = true;
    };
  }, [requestKey, isFolder, name, open, kind]);

  if (!src) {
    // Loading (first fetch of this icon in flight), or every fallback failed — a
    // neutral chrome glyph, never a crash or a broken-image icon.
    const Glyph = isFolder ? FolderFallbackGlyph : FileFallbackGlyph;
    return (
      <Glyph size={size} className={className} color="var(--color-muted)" strokeWidth={1.75} aria-hidden />
    );
  }

  return (
    <img
      src={src}
      width={size}
      height={size}
      alt=""
      aria-hidden
      className={className}
      style={{ flexShrink: 0, display: "inline-block", objectFit: "contain" }}
      draggable={false}
    />
  );
}
