/**
 * GENERATED by scripts/generate-icon-manifest.mjs — do not hand-edit.
 * Regenerate: `node scripts/generate-icon-manifest.mjs` (after bumping
 * material-icon-theme or editing the curated lists in that script).
 *
 * A small, curated slice of material-icon-theme's manifest (see that
 * script's header for why) plus one explicit lazy `import()` per curated
 * icon SVG — a small, fixed routing table instead of the full package's
 * `import.meta.glob` over all ~1250 icons, so a cold boot only pays for
 * the icons this curated set can name, not the whole pack's lookup tables.
 */
import type { FileKind } from "../../types";

export interface CuratedManifest {
  file: string;
  folder: string;
  folderExpanded: string;
  fileExtensions: Record<string, string>;
  fileNames: Record<string, string>;
  folderNames: Record<string, string>;
  folderNamesExpanded: Record<string, string>;
}

export const curatedManifest: CuratedManifest = {
  "file": "file",
  "folder": "folder",
  "folderExpanded": "folder-open",
  "fileExtensions": {
    "md": "markdown",
    "markdown": "markdown",
    "mdx": "mdx",
    "ts": "typescript",
    "tsx": "react_ts",
    "js": "javascript",
    "jsx": "react",
    "mjs": "javascript",
    "cjs": "javascript",
    "json": "json",
    "jsonc": "json",
    "css": "css",
    "scss": "sass",
    "sass": "sass",
    "less": "less",
    "html": "html",
    "htm": "html",
    "csv": "table",
    "tsv": "table",
    "png": "image",
    "jpg": "image",
    "jpeg": "image",
    "gif": "image",
    "svg": "svg",
    "webp": "image",
    "ico": "image",
    "yml": "yaml",
    "yaml": "yaml",
    "toml": "toml",
    "xml": "xml",
    "sh": "console",
    "bash": "console",
    "zsh": "console",
    "py": "python",
    "rs": "rust",
    "go": "go",
    "java": "java",
    "rb": "ruby",
    "php": "php",
    "sql": "database",
    "lock": "lock",
    "txt": "document",
    "pdf": "pdf",
    "zip": "zip",
    "env": "tune",
    "ini": "settings",
    "conf": "settings",
    "log": "log",
    "vue": "vue",
    "svelte": "svelte",
    "graphql": "graphql",
    "gql": "graphql",
    "wasm": "webassembly"
  },
  "fileNames": {
    "package.json": "nodejs",
    "package-lock.json": "nodejs",
    "tsconfig.json": "tsconfig",
    "readme.md": "readme",
    "license": "license",
    ".gitignore": "git",
    ".gitattributes": "git",
    "dockerfile": "docker",
    "docker-compose.yml": "docker",
    "vite.config.ts": "vite",
    "webpack.config.js": "webpack",
    ".eslintrc": "eslint",
    ".prettierrc": "prettier",
    "makefile": "makefile",
    ".npmrc": "npm",
    "go.mod": "go-mod",
    "requirements.txt": "python-misc",
    "architecture.md": "architecture"
  },
  "folderNames": {
    "src": "folder-src",
    "notes": "folder-docs",
    "assets": "folder-resource",
    "docs": "folder-docs",
    "dist": "folder-dist",
    "build": "folder-dist",
    "node_modules": "folder-node",
    "public": "folder-public",
    "test": "folder-test",
    "tests": "folder-test",
    "__tests__": "folder-test",
    "components": "folder-components",
    "images": "folder-images",
    "img": "folder-images",
    "styles": "folder-css",
    "scripts": "folder-scripts",
    "config": "folder-config",
    "lib": "folder-lib",
    "utils": "folder-utils",
    "hooks": "folder-hook",
    "api": "folder-api",
    "server": "folder-server",
    "client": "folder-client",
    ".git": "folder-git",
    ".github": "folder-github",
    ".vscode": "folder-vscode"
  },
  "folderNamesExpanded": {
    "src": "folder-src-open",
    "notes": "folder-docs-open",
    "assets": "folder-resource-open",
    "docs": "folder-docs-open",
    "dist": "folder-dist-open",
    "build": "folder-dist-open",
    "node_modules": "folder-node-open",
    "public": "folder-public-open",
    "test": "folder-test-open",
    "tests": "folder-test-open",
    "__tests__": "folder-test-open",
    "components": "folder-components-open",
    "images": "folder-images-open",
    "img": "folder-images-open",
    "styles": "folder-css-open",
    "scripts": "folder-scripts-open",
    "config": "folder-config-open",
    "lib": "folder-lib-open",
    "utils": "folder-utils-open",
    "hooks": "folder-hook-open",
    "api": "folder-api-open",
    "server": "folder-server-open",
    "client": "folder-client-open",
    ".git": "folder-git-open",
    ".github": "folder-github-open",
    ".vscode": "folder-vscode-open"
  }
};

/** One explicit dynamic import per curated icon — Vite code-splits each into
 * its own tiny chunk, fetched only if/when that specific icon is rendered. */
export const curatedIconLoaders: Record<string, () => Promise<string>> = {
  "architecture": () =>
    import("material-icon-theme/icons/architecture.svg?url").then((m) => m.default),
  "console": () =>
    import("material-icon-theme/icons/console.svg?url").then((m) => m.default),
  "css": () =>
    import("material-icon-theme/icons/css.svg?url").then((m) => m.default),
  "database": () =>
    import("material-icon-theme/icons/database.svg?url").then((m) => m.default),
  "docker": () =>
    import("material-icon-theme/icons/docker.svg?url").then((m) => m.default),
  "document": () =>
    import("material-icon-theme/icons/document.svg?url").then((m) => m.default),
  "eslint": () =>
    import("material-icon-theme/icons/eslint.svg?url").then((m) => m.default),
  "file": () =>
    import("material-icon-theme/icons/file.svg?url").then((m) => m.default),
  "folder": () =>
    import("material-icon-theme/icons/folder.svg?url").then((m) => m.default),
  "folder-api": () =>
    import("material-icon-theme/icons/folder-api.svg?url").then((m) => m.default),
  "folder-api-open": () =>
    import("material-icon-theme/icons/folder-api-open.svg?url").then((m) => m.default),
  "folder-client": () =>
    import("material-icon-theme/icons/folder-client.svg?url").then((m) => m.default),
  "folder-client-open": () =>
    import("material-icon-theme/icons/folder-client-open.svg?url").then((m) => m.default),
  "folder-components": () =>
    import("material-icon-theme/icons/folder-components.svg?url").then((m) => m.default),
  "folder-components-open": () =>
    import("material-icon-theme/icons/folder-components-open.svg?url").then((m) => m.default),
  "folder-config": () =>
    import("material-icon-theme/icons/folder-config.svg?url").then((m) => m.default),
  "folder-config-open": () =>
    import("material-icon-theme/icons/folder-config-open.svg?url").then((m) => m.default),
  "folder-css": () =>
    import("material-icon-theme/icons/folder-css.svg?url").then((m) => m.default),
  "folder-css-open": () =>
    import("material-icon-theme/icons/folder-css-open.svg?url").then((m) => m.default),
  "folder-dist": () =>
    import("material-icon-theme/icons/folder-dist.svg?url").then((m) => m.default),
  "folder-dist-open": () =>
    import("material-icon-theme/icons/folder-dist-open.svg?url").then((m) => m.default),
  "folder-docs": () =>
    import("material-icon-theme/icons/folder-docs.svg?url").then((m) => m.default),
  "folder-docs-open": () =>
    import("material-icon-theme/icons/folder-docs-open.svg?url").then((m) => m.default),
  "folder-git": () =>
    import("material-icon-theme/icons/folder-git.svg?url").then((m) => m.default),
  "folder-git-open": () =>
    import("material-icon-theme/icons/folder-git-open.svg?url").then((m) => m.default),
  "folder-github": () =>
    import("material-icon-theme/icons/folder-github.svg?url").then((m) => m.default),
  "folder-github-open": () =>
    import("material-icon-theme/icons/folder-github-open.svg?url").then((m) => m.default),
  "folder-hook": () =>
    import("material-icon-theme/icons/folder-hook.svg?url").then((m) => m.default),
  "folder-hook-open": () =>
    import("material-icon-theme/icons/folder-hook-open.svg?url").then((m) => m.default),
  "folder-images": () =>
    import("material-icon-theme/icons/folder-images.svg?url").then((m) => m.default),
  "folder-images-open": () =>
    import("material-icon-theme/icons/folder-images-open.svg?url").then((m) => m.default),
  "folder-lib": () =>
    import("material-icon-theme/icons/folder-lib.svg?url").then((m) => m.default),
  "folder-lib-open": () =>
    import("material-icon-theme/icons/folder-lib-open.svg?url").then((m) => m.default),
  "folder-node": () =>
    import("material-icon-theme/icons/folder-node.svg?url").then((m) => m.default),
  "folder-node-open": () =>
    import("material-icon-theme/icons/folder-node-open.svg?url").then((m) => m.default),
  "folder-open": () =>
    import("material-icon-theme/icons/folder-open.svg?url").then((m) => m.default),
  "folder-public": () =>
    import("material-icon-theme/icons/folder-public.svg?url").then((m) => m.default),
  "folder-public-open": () =>
    import("material-icon-theme/icons/folder-public-open.svg?url").then((m) => m.default),
  "folder-resource": () =>
    import("material-icon-theme/icons/folder-resource.svg?url").then((m) => m.default),
  "folder-resource-open": () =>
    import("material-icon-theme/icons/folder-resource-open.svg?url").then((m) => m.default),
  "folder-scripts": () =>
    import("material-icon-theme/icons/folder-scripts.svg?url").then((m) => m.default),
  "folder-scripts-open": () =>
    import("material-icon-theme/icons/folder-scripts-open.svg?url").then((m) => m.default),
  "folder-server": () =>
    import("material-icon-theme/icons/folder-server.svg?url").then((m) => m.default),
  "folder-server-open": () =>
    import("material-icon-theme/icons/folder-server-open.svg?url").then((m) => m.default),
  "folder-src": () =>
    import("material-icon-theme/icons/folder-src.svg?url").then((m) => m.default),
  "folder-src-open": () =>
    import("material-icon-theme/icons/folder-src-open.svg?url").then((m) => m.default),
  "folder-test": () =>
    import("material-icon-theme/icons/folder-test.svg?url").then((m) => m.default),
  "folder-test-open": () =>
    import("material-icon-theme/icons/folder-test-open.svg?url").then((m) => m.default),
  "folder-utils": () =>
    import("material-icon-theme/icons/folder-utils.svg?url").then((m) => m.default),
  "folder-utils-open": () =>
    import("material-icon-theme/icons/folder-utils-open.svg?url").then((m) => m.default),
  "folder-vscode": () =>
    import("material-icon-theme/icons/folder-vscode.svg?url").then((m) => m.default),
  "folder-vscode-open": () =>
    import("material-icon-theme/icons/folder-vscode-open.svg?url").then((m) => m.default),
  "git": () =>
    import("material-icon-theme/icons/git.svg?url").then((m) => m.default),
  "go": () =>
    import("material-icon-theme/icons/go.svg?url").then((m) => m.default),
  "go-mod": () =>
    import("material-icon-theme/icons/go-mod.svg?url").then((m) => m.default),
  "graphql": () =>
    import("material-icon-theme/icons/graphql.svg?url").then((m) => m.default),
  "html": () =>
    import("material-icon-theme/icons/html.svg?url").then((m) => m.default),
  "image": () =>
    import("material-icon-theme/icons/image.svg?url").then((m) => m.default),
  "java": () =>
    import("material-icon-theme/icons/java.svg?url").then((m) => m.default),
  "javascript": () =>
    import("material-icon-theme/icons/javascript.svg?url").then((m) => m.default),
  "json": () =>
    import("material-icon-theme/icons/json.svg?url").then((m) => m.default),
  "less": () =>
    import("material-icon-theme/icons/less.svg?url").then((m) => m.default),
  "license": () =>
    import("material-icon-theme/icons/license.svg?url").then((m) => m.default),
  "lock": () =>
    import("material-icon-theme/icons/lock.svg?url").then((m) => m.default),
  "log": () =>
    import("material-icon-theme/icons/log.svg?url").then((m) => m.default),
  "makefile": () =>
    import("material-icon-theme/icons/makefile.svg?url").then((m) => m.default),
  "markdown": () =>
    import("material-icon-theme/icons/markdown.svg?url").then((m) => m.default),
  "mdx": () =>
    import("material-icon-theme/icons/mdx.svg?url").then((m) => m.default),
  "nodejs": () =>
    import("material-icon-theme/icons/nodejs.svg?url").then((m) => m.default),
  "npm": () =>
    import("material-icon-theme/icons/npm.svg?url").then((m) => m.default),
  "pdf": () =>
    import("material-icon-theme/icons/pdf.svg?url").then((m) => m.default),
  "php": () =>
    import("material-icon-theme/icons/php.svg?url").then((m) => m.default),
  "prettier": () =>
    import("material-icon-theme/icons/prettier.svg?url").then((m) => m.default),
  "python": () =>
    import("material-icon-theme/icons/python.svg?url").then((m) => m.default),
  "python-misc": () =>
    import("material-icon-theme/icons/python-misc.svg?url").then((m) => m.default),
  "react": () =>
    import("material-icon-theme/icons/react.svg?url").then((m) => m.default),
  "react_ts": () =>
    import("material-icon-theme/icons/react_ts.svg?url").then((m) => m.default),
  "readme": () =>
    import("material-icon-theme/icons/readme.svg?url").then((m) => m.default),
  "ruby": () =>
    import("material-icon-theme/icons/ruby.svg?url").then((m) => m.default),
  "rust": () =>
    import("material-icon-theme/icons/rust.svg?url").then((m) => m.default),
  "sass": () =>
    import("material-icon-theme/icons/sass.svg?url").then((m) => m.default),
  "settings": () =>
    import("material-icon-theme/icons/settings.svg?url").then((m) => m.default),
  "svelte": () =>
    import("material-icon-theme/icons/svelte.svg?url").then((m) => m.default),
  "svg": () =>
    import("material-icon-theme/icons/svg.svg?url").then((m) => m.default),
  "table": () =>
    import("material-icon-theme/icons/table.svg?url").then((m) => m.default),
  "toml": () =>
    import("material-icon-theme/icons/toml.svg?url").then((m) => m.default),
  "tsconfig": () =>
    import("material-icon-theme/icons/tsconfig.svg?url").then((m) => m.default),
  "tune": () =>
    import("material-icon-theme/icons/tune.svg?url").then((m) => m.default),
  "typescript": () =>
    import("material-icon-theme/icons/typescript.svg?url").then((m) => m.default),
  "vite": () =>
    import("material-icon-theme/icons/vite.svg?url").then((m) => m.default),
  "vue": () =>
    import("material-icon-theme/icons/vue.svg?url").then((m) => m.default),
  "webassembly": () =>
    import("material-icon-theme/icons/webassembly.svg?url").then((m) => m.default),
  "webpack": () =>
    import("material-icon-theme/icons/webpack.svg?url").then((m) => m.default),
  "xml": () =>
    import("material-icon-theme/icons/xml.svg?url").then((m) => m.default),
  "yaml": () =>
    import("material-icon-theme/icons/yaml.svg?url").then((m) => m.default),
  "zip": () =>
    import("material-icon-theme/icons/zip.svg?url").then((m) => m.default),
};

export const KIND_FALLBACK_EXT: Partial<Record<FileKind, string>> = {
  md: "md",
  ts: "ts",
  tsx: "tsx",
  json: "json",
  css: "css",
  csv: "csv",
  image: "png",
};
