/**
 * Full-manifest fallback loader — used only when `FileIcon`'s curated table
 * (`materialIcons.curated.ts`, generated by `scripts/generate-icon-manifest.mjs`)
 * doesn't recognize a file's name/extension. This module is meant to be
 * reached via a dynamic `import("./materialIconLoader")`, never a static
 * one: it owns the *entire* upstream `material-icon-theme` manifest
 * (~450KB) and an `import.meta.glob` covering all ~1250 icon SVGs (~160KB
 * routing table) — real weight that a curated-hit cold boot should never
 * pay for. See `FileIcon.tsx`'s header for the full two-tier rationale.
 *
 * Files only, deliberately: folder *names* are effectively open-ended (any
 * real project's root/subfolder names are as likely to be arbitrary as
 * conventional), so even the full ~4650-entry `folderNames` map rarely adds
 * a hit beyond what's already in the curated set — not worth a 600KB fetch
 * on the (common) chance it doesn't help. Unmatched folders just keep the
 * curated pack's default `folder`/`folder-open` glyph.
 */
export interface MaterialIconManifest {
  iconDefinitions: Record<string, { iconPath: string }>;
  fileNames: Record<string, string>;
  fileExtensions: Record<string, string>;
  folderNames: Record<string, string>;
  folderNamesExpanded: Record<string, string>;
  file: string;
  folder: string;
  folderExpanded: string;
}

// Parsed at runtime (not a typed JSON import) so TS never has to structurally
// type ~10k literal keys from the manifest — cast once to the small shape
// actually used. Cached: fetched at most once per page load.
let manifestPromise: Promise<MaterialIconManifest> | undefined;
export function getManifest(): Promise<MaterialIconManifest> {
  manifestPromise ??= import("material-icon-theme/dist/material-icons.json?raw").then(
    (mod) => JSON.parse(mod.default) as MaterialIconManifest,
  );
  return manifestPromise;
}

// Lazy, per-icon dynamic imports over the *entire* pack — only reached once
// resolution already fell through the curated table, and even then only the
// specific icon file resolved below is ever fetched.
const ICON_MODULES = import.meta.glob("/node_modules/material-icon-theme/icons/*.svg", {
  query: "?url",
  import: "default",
}) as Record<string, () => Promise<string>>;

const urlCache = new Map<string, Promise<string | undefined>>();

function iconPathToModuleKey(iconPath: string): string {
  const filename = iconPath.replace("./../icons/", "");
  return `/node_modules/material-icon-theme/icons/${filename}`;
}

export function loadIconUrl(manifest: MaterialIconManifest, iconDefKey: string): Promise<string | undefined> {
  const cached = urlCache.get(iconDefKey);
  if (cached) return cached;
  const def = manifest.iconDefinitions[iconDefKey];
  const modulePath = def ? iconPathToModuleKey(def.iconPath) : undefined;
  const loader = modulePath ? ICON_MODULES[modulePath] : undefined;
  const promise = loader ? loader().catch(() => undefined) : Promise.resolve(undefined);
  urlCache.set(iconDefKey, promise);
  return promise;
}

/**
 * Full-manifest file resolution, returning `undefined` when it can't do any
 * better than the curated default already on screen (so the caller never
 * pays for a redundant fetch of the same generic glyph).
 */
export function resolveFileIconKey(
  manifest: MaterialIconManifest,
  name: string | undefined,
  curatedFallbackKey: string,
): string | undefined {
  const lower = name?.toLowerCase();
  if (!lower) return undefined;
  const byName = manifest.fileNames[lower];
  if (byName) return byName;
  const parts = lower.split(".");
  for (let i = 1; i < parts.length; i++) {
    const ext = parts.slice(i).join(".");
    const hit = manifest.fileExtensions[ext];
    if (hit) return hit;
  }
  const fallback = manifest.file;
  return fallback !== curatedFallbackKey ? fallback : undefined;
}
